jbd-sprint4-day2-Abdiev003/food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

from accounts.views import CustomAuthToken

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include("stories.urls")),
    path('api/', include('stories.api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/auth/login/', CustomAuthToken.as_view())
)

jbd-sprint4-day2-Abdiev003/stories/api/urls.py
from django.urls import path
from stories.api.views import RecipeAPIView, RecipeDetailAPIView, SubscribeAPIView

app_name = 'api'

urlpatterns = [
    path('recipes/', RecipeAPIView.as_view(), name='recipes_api'),
    path('recipes/<int:pk>/', RecipeDetailAPIView.as_view(), name='recipes_detail_api'),
    path('subscribe/', SubscribeAPIView.as_view(), name='subscribe')
]

jbd-sprint4-day2-Abdiev003/stories/urls.py
from django.urls import path

from .views import (
    HomePage, AboutPage, StoriesPage, like_recipe, liked_recipe_page,
    RecipeListView,
    RecipeDetailView,
    ContactView,
    CreateRecipeView, dump_database_view
    # RecipesPage,
)

app_name = "stories"

urlpatterns = [
    path('', HomePage, name="index"),
    path('about/', AboutPage, name="about"),
    path('stories/', StoriesPage, name="stories"),
    path('recipes/', RecipeListView.as_view(), name="recipes"),
    path('create-recipe/', CreateRecipeView.as_view(), name="create_recipe"),
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('contact/', ContactView.as_view(), name="contact"),
    path('like/', like_recipe, name='like'),
    path('liked_recipe_page/', liked_recipe_page, name='liked_recipe_page'),
    path('dump-my-database/', dump_database_view, name='dump_database_view'),
]

jbd-sprint4-day2-Abdiev003/stories/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from slugify import slugify

User = get_user_model()


class Tag(models.Model):
    title = models.CharField('Title', max_length=50)

    # moderation's
    order = models.PositiveIntegerField('Order', default=1)
    is_published = models.BooleanField('Is Published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ('created_at',)

    def __str__(self):
        return self.title


class Category(models.Model):
    # information's
    title = models.CharField('Title', max_length=127)
    image = models.ImageField('Image', upload_to='category_images', )

    # moderation's
    order = models.PositiveIntegerField('Order', default=1)
    is_published = models.BooleanField('Is Published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('order', '-created_at')

    def __str__(self):
        return self.title


# class TagRecipeRel()
#     tag
#     recipe =


class Recipe(models.Model):
    """
    in this table you can store recipes like: 'Alma Piroqu, Gilas Piroqu,'
    """
    # CATEGORY_OPTIONS = (
    #     (1, 'Dessert'),
    #     (2, 'Salat'),
    #     (3, 'Xalodni'),
    # )
    # relation's
    category = models.ForeignKey(Category, verbose_name='Category',
                                 on_delete=models.CASCADE, db_index=True, related_name='recipes')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', db_index=True, blank=True, )
    author = models.ForeignKey(User, verbose_name='author', on_delete=models.CASCADE, db_index=True,
                               related_name='recipes', )

    # information's
    title = models.CharField('Basliq', max_length=127)
    slug = models.SlugField('Slug', max_length=155,)
    short_description = models.CharField('Qisa Mezmun', max_length=255)
    image = models.ImageField('Sekil', upload_to='recipe_images', )

    # category = models.IntegerField('Kategoriya', choices=CATEGORY_OPTIONS)
    description = RichTextUploadingField('Mezmun', )

    # moderation's
    order = models.PositiveIntegerField('Order', default=1)
    is_published = models.BooleanField('Is Published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Resept'
        verbose_name_plural = 'Reseptler'
        ordering = ('order', '-created_at')

    def __str__(self):
        return f"{self.title} Kategoriyasi: {self.category.title}"

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     return super(Recipe, self).save(*args, **kwargs)

    def get_absolute_url(self):
        if self.slug:
            return reverse_lazy('stories:recipe_detail', kwargs={'slug': self.slug})
        return reverse_lazy('stories:recipe_detail', kwargs={'slug': 'sjkdnf'})

    @property
    def serialized_data(self):
        return {
            'title': self.title,
            'description': self.description,
            'short_description': self.short_description,
            'slug': self.slug,
            'created_at': str(self.created_at),
        }


# resept = Recipe()
# resept.category
#
# kategori = Category()
# kategori.recipes.all()


class Contact(models.Model):
    """
    in this table you can store user contact info
    """

    # information's
    full_name = models.CharField('Tam adi', max_length=127)
    email = models.EmailField('E-poct', max_length=63)
    subject = models.CharField('Movzu', max_length=255)
    message = models.TextField('Mesaj', help_text='Bu qutuya mesajinizi ehateli sekilde daxil edin')

    # moderation's
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.email}"


class Comment(models.Model):
    # relation's
    recipe = models.ForeignKey(Recipe, verbose_name='Recipe', on_delete=models.CASCADE, db_index=True,
                               related_name='comment')
    author = models.ForeignKey(User, verbose_name='Author', on_delete=models.CASCADE, db_index=True,
                               related_name='comment')
    parent_comment = models.ForeignKey('self', verbose_name='Parent Comment', on_delete=models.CASCADE, db_index=True,
                                       related_name='sub_comments', blank=True, null=True)

    # information's
    content = models.TextField('Content')

    # moderation's
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}"


class Subscriber(models.Model):
    email = models.EmailField(_('Email'), unique=True, max_length=40)

    # moderation's
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.email}"

jbd-sprint4-day2-Abdiev003/stories/api/views.py
import json

from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework import status
from stories.models import Recipe, Subscriber
from stories.api.serializers import RecipeSerializer, RecipeCreateSerializer, SubscriberSerializer
# from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView


class RecipeAPIView(ListCreateAPIView):
    queryset = Recipe.objects.filter(is_published=True)
    serializer_class = RecipeSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return self.serializer_class
        return RecipeCreateSerializer


class RecipeDetailAPIView(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Recipe.objects.filter(is_published=True)
    serializer_class = RecipeSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return self.serializer_class
        return RecipeCreateSerializer


class SubscribeAPIView(CreateAPIView):
    queryset = Subscriber.objects.filter(is_active=True)
    serializer_class = SubscriberSerializer


#
# @api_view(('GET', 'POST'))
# def recipes(request):
#     if request.method == 'POST':
#         recipe_data = request.data
#         serializer = RecipeCreateSerializer(data=recipe_data, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)
#     recipes = Recipe.objects.filter(is_published=True)
#     serializer = RecipeSerializer(recipes, many=True, context={'request': request})
#     return Response(serializer.data)


# class RecipeAPIView(APIView):
#
#     def get(self, request, *args, **kwargs):
#         recipes = Recipe.objects.filter(is_published=True)
#         filter_by = json.loads(json.dumps(request.GET))
#         if filter_by:
#             recipes = recipes.filter(**filter_by)  # title=resept
#         serializer = RecipeSerializer(recipes, many=True, context={'request': request})
#         return Response(serializer.data)
#
#     def post(self, request, *args, **kwargs):
#         recipe_data = request.data
#         serializer = RecipeCreateSerializer(data=recipe_data, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)


# class RecipeDetailAPIView(APIView):
#
#     def get(self, request, *args, **kwargs):
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeSerializer(recipe, context={'request': request})
#         return Response(serializer.data)
#
#     def put(self, request, *args, **kwargs):
#         recipe_data = request.data
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeCreateSerializer(data=recipe_data, instance=recipe, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_200_OK)
#
#     def patch(self, request, *args, **kwargs):
#         recipe_data = request.data
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeCreateSerializer(data=recipe_data, instance=recipe,
#                                             partial=True, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_200_OK)
#
#     def delete(self, request, *args, **kwargs):
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True)
#         if not recipe:
#             raise NotFound
#         recipe.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)

jbd-sprint4-day2-Abdiev003/stories/views.py
import math

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView
)

from stories.forms import ContactForm, RecipesForm
from stories.models import Recipe, Tag, Contact
from stories.tasks import dump_database


def dump_database_view(request):
    dump_database.delay()
    return HttpResponse('Database dump olundu...')


def HomePage(request):
    return render(request, "index.html")


def AboutPage(request):
    context = {
        "title": "About Stories",
        "description": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia",
        "dailyvisitors": 200,
        "stories": 200,
        "recipes": 300,
        "user": 40,
    }
    return render(request, "about.html", context)


def StoriesPage(request):
    return render(request, "strories.html", )


# @login_required
# def RecipesPage(request):
#     page = int(request.GET.get('page', 1))
#     per_count = 2
#     all_recipes_count = Recipe.objects.filter(is_published=True).count()
#     recipes = Recipe.objects.filter(is_published=True)[per_count*(page-1):page*per_count]
#     page_count = math.ceil(all_recipes_count/per_count)
#     page_range = range(1, page_count+1)
#     arr = ['idris', 'emrah', 'eli']
#     welcome_msg = '<h1>Welcome</h1>'
#     previous_page = page - 1 if not page == 1 else page
#     next_page = page + 1 if not page == page_count else page
#     context = {
#         'recipe_list': recipes,
#         'welcome_msg': welcome_msg,
#         'page_range': page_range,
#         'current_page': page,
#         'previous_page': previous_page,
#         'next_page': next_page,
#         'arr': arr
#     }
#     return render(request, "recipes.html", context)


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes.html'
    paginate_by = 2

    # context_object_name = 'recipe_list'
    # queryset = Recipe.objects.filter(is_published=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        tags = self.request.GET.get('tags')
        print(tags)
        queryset = queryset.filter(is_published=True)
        if tags:
            queryset = queryset.filter(tags__id=tags)
        return queryset


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipe-detail.html'
    context_object_name = 'recipe_tag'
    queryset = Recipe.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


# def ContactPage(request):
#     form = ContactForm()
#     if request.method == 'POST':
#         form = ContactForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Sizin muracietiniz qebul edildi.')
#             return redirect('/recipes/')
#     context = {
#         'form': form
#     }
#     return render(request, "contact.html", context)


class ContactView(CreateView):
    form_class = ContactForm
    # fields = '__all__'
    # model = Contact
    template_name = 'contact.html'
    success_url = reverse_lazy('stories:index')

    def form_valid(self, form):
        result = super(ContactView, self).form_valid(form)
        messages.success(self.request, 'Sizin muracietiniz qebul edildi.')
        return result


class CreateRecipeView(LoginRequiredMixin, CreateView):
    form_class = RecipesForm
    template_name = 'recipes-add.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateRecipeView, self).form_valid(form)


def like_recipe(request):
    if request.method == 'POST':
        liked_recipes = request.COOKIES.get('liked_recipes', '')
        recipe_id = request.POST.get('recipe_id')

        html = render_to_string('successfully_added.html')
        response = HttpResponse(html)
        if recipe_id not in liked_recipes.split(','):
            recipe_ids = f'{liked_recipes}{recipe_id},'
            request.session['recipe_ids'] = recipe_ids
            response.set_cookie('liked_recipes', recipe_ids)
        return response


def liked_recipe_page(request):
    liked_recipes = request.COOKIES.get('liked_recipes', '')
    print(dict(request.session))
    recipes = Recipe.objects.filter(id__in=list(map(int, liked_recipes.split(',')[:-1])))
    context = {
        'recipe_list': recipes,
        'liked_recipe_page': True
    }
    return render(request, "recipes.html", context)

jbd-sprint4-day2-Abdiev003/stories/templates/recipe-detail.html
{% extends 'base.html' %}
{% load static custom_tags %}

{% block title %} Recipes Detail Page {% endblock %}

{% block content %}


<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'assets/images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{ recipe_tag.title }}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'stories:index' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>{{ recipe_tag.title }}<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 order-lg-last ftco-animate">
                {{ recipe_tag.description|safe }}


                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for rec in recipe_tag.tags.all %}
                        <a href="#" class="tag-cloud-link">{{ rec }}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{ recipe_tag.author }}</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5"><span id="comment-count"></span> Comments</h3>
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>

                            <ul class="children">
                                <li class="comment">
                                    <div class="vcard bio">
                                        <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <h3>John Doe</h3>
                                        <div class="meta">October 03, 2018 at 2:21pm</div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem
                                            laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe
                                            enim sapiente iste iure! Quam voluptas earum impedit necessitatibus,
                                            nihil?</p>
                                        <p><a href="#" class="reply">Reply</a></p>
                                    </div>


                                    <ul class="children">
                                        <li class="comment">
                                            <div class="vcard bio">
                                                <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                                            </div>
                                            <div class="comment-body">
                                                <h3>John Doe</h3>
                                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur
                                                    quidem laborum necessitatibus, ipsam impedit vitae autem, eum
                                                    officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum
                                                    impedit necessitatibus, nihil?</p>
                                                <p><a href="#" class="reply">Reply</a></p>
                                            </div>

                                            <ul class="children">
                                                <li class="comment">
                                                    <div class="vcard bio">
                                                        <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                                                    </div>
                                                    <div class="comment-body">
                                                        <h3>John Doe</h3>
                                                        <div class="meta">October 03, 2018 at 2:21pm</div>
                                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                                            Pariatur quidem laborum necessitatibus, ipsam impedit vitae
                                                            autem, eum officia, fugiat saepe enim sapiente iste iure!
                                                            Quam voluptas earum impedit necessitatibus, nihil?</p>
                                                        <p><a href="#" class="reply">Reply</a></p>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>John Doe</h3>
                                <div class="meta">October 03, 2018 at 2:21pm</div>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                    necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente
                                    iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" class="p-5 bg-light">
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {% get_categories True as categories %}
                        {% for category in categories %}
                        <li><a href="#">{{ category.title }} <span>(0)</span></a></li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Stories</h3>
                    {% for story in stories %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ story.image.url }});"></a>
                        <div class="text">
                            <h3><a href="#">{{ story.title }}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span>{{ story.created_at|date:"F d, Y" }}</a></div>
                                <div><a href="#"><span class="icon-person"></span>{{ story.author }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                           <a href="{% url 'stories:recipes' %}?tags={{ tag.id }}" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->


{% endblock %}
{% block js %}
    <script>
        window.URLS['recipeDetail'] = '{% url "api:recipes_detail_api" '1234567' %}'
            .replace('1234567', {{ recipe_tag.id }});
    </script>


{% endblock %}

jbd-sprint4-day2-Abdiev003/stories/templates/recipes-add.html
{% extends 'base.html' %}
{% load static custom_tags %}

{% block title %} Recipe Add Page {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block content %}
    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                            {% for error in field.errors %}
                                <li class="alert alert-danger">{{ error }}</li>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock %}