jbd-sprint4-day2-Abdiev003/accounts/urls.py
from django.urls import path, re_path

from accounts.views import register, activate, login, logout, change_password, UserProfileView, UserEditProfileView

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})/$',
            activate, name='activate'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('change-password/', change_password, name='change_password'),
    path('user-profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('edit-profile/', UserEditProfileView.as_view(), name='edit_profile'),
]

jbd-sprint4-day2-Abdiev003/food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

from accounts.views import CustomAuthToken

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include("stories.urls")),
    path('api/', include('stories.api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/auth/login/', CustomAuthToken.as_view())
)

jbd-sprint4-day2-Abdiev003/stories/api/urls.py
from django.urls import path
from stories.api.views import RecipeAPIView, RecipeDetailAPIView, SubscribeAPIView

app_name = 'api'

urlpatterns = [
    path('recipes/', RecipeAPIView.as_view(), name='recipes_api'),
    path('recipes/<int:pk>/', RecipeDetailAPIView.as_view(), name='recipes_detail_api'),
    path('subscribe/', SubscribeAPIView.as_view(), name='subscribe')
]

jbd-sprint4-day2-Abdiev003/stories/urls.py
from django.urls import path

from .views import (
    HomePage, AboutPage, StoriesPage, like_recipe, liked_recipe_page,
    RecipeListView,
    RecipeDetailView,
    ContactView,
    CreateRecipeView, dump_database_view
    # RecipesPage,
)

app_name = "stories"

urlpatterns = [
    path('', HomePage, name="index"),
    path('about/', AboutPage, name="about"),
    path('stories/', StoriesPage, name="stories"),
    path('recipes/', RecipeListView.as_view(), name="recipes"),
    path('create-recipe/', CreateRecipeView.as_view(), name="create_recipe"),
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('contact/', ContactView.as_view(), name="contact"),
    path('like/', like_recipe, name='like'),
    path('liked_recipe_page/', liked_recipe_page, name='liked_recipe_page'),
    path('dump-my-database/', dump_database_view, name='dump_database_view'),
]

jbd-sprint4-day2-Abdiev003/stories/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from ckeditor_uploader.widgets import CKEditorUploadingWidget

from stories.models import Contact, Recipe


from stories.utils.validators import mail_validator


class ContactForm(forms.ModelForm):
    # full_name = forms.CharField(label='Full name', max_length=127, widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Your name'
    # }))
    # email = forms.EmailField(label='Email', validators=(mail_validator,),
    #                          widget=forms.EmailInput(attrs={
    #                              'class': 'form-control',
    #                              'placeholder': 'Your email'
    #                          }))

    class Meta:
        model = Contact
        fields = (
            'email',
            'full_name',
            'subject',
            'message'
        )
        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Your name')
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': _('Your email')
            }),
            'subject': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Subject'
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Message',
                'cols': 50,
            })
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('gmail.com'):
            raise forms.ValidationError('Daxil edilen email yanliz gmail hesabi olmalidir')
        return email

    # full_name = forms.CharField(label='Full name', max_length=127, widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Your name'
    # }))
    # email = forms.EmailField(label='Email', max_length=63, widget=forms.EmailInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Your email'
    # }))
    # subject = forms.CharField(label='Subject', max_length=255,  widget=forms.EmailInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Subject'
    # }))
    # message = forms.CharField(label='Message', widget=forms.Textarea(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Message',
    #     'cols': 50,
    # }))


class RecipesForm(forms.ModelForm):
    # description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Recipe
        fields = ('title', 'short_description', 'description', 'image', 'category', 'tags',)
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Resept Başlığı'),
            }),
            'short_description': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Qisa Mezmun'),
            }),
            'description': CKEditorUploadingWidget(attrs={
                'class': 'form-control',
                'placeholder': 'Mezmun',
            }),
            'category': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Category',
            }),
            'tags': forms.SelectMultiple(attrs={
                'class': 'form-control',
                'placeholder': 'Tags',
            }),
        }

jbd-sprint4-day2-Abdiev003/stories/api/views.py
import json

from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework import status
from stories.models import Recipe, Subscriber
from stories.api.serializers import RecipeSerializer, RecipeCreateSerializer, SubscriberSerializer
# from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView


class RecipeAPIView(ListCreateAPIView):
    queryset = Recipe.objects.filter(is_published=True)
    serializer_class = RecipeSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return self.serializer_class
        return RecipeCreateSerializer


class RecipeDetailAPIView(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Recipe.objects.filter(is_published=True)
    serializer_class = RecipeSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return self.serializer_class
        return RecipeCreateSerializer


class SubscribeAPIView(CreateAPIView):
    queryset = Subscriber.objects.filter(is_active=True)
    serializer_class = SubscriberSerializer


#
# @api_view(('GET', 'POST'))
# def recipes(request):
#     if request.method == 'POST':
#         recipe_data = request.data
#         serializer = RecipeCreateSerializer(data=recipe_data, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)
#     recipes = Recipe.objects.filter(is_published=True)
#     serializer = RecipeSerializer(recipes, many=True, context={'request': request})
#     return Response(serializer.data)


# class RecipeAPIView(APIView):
#
#     def get(self, request, *args, **kwargs):
#         recipes = Recipe.objects.filter(is_published=True)
#         filter_by = json.loads(json.dumps(request.GET))
#         if filter_by:
#             recipes = recipes.filter(**filter_by)  # title=resept
#         serializer = RecipeSerializer(recipes, many=True, context={'request': request})
#         return Response(serializer.data)
#
#     def post(self, request, *args, **kwargs):
#         recipe_data = request.data
#         serializer = RecipeCreateSerializer(data=recipe_data, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)


# class RecipeDetailAPIView(APIView):
#
#     def get(self, request, *args, **kwargs):
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeSerializer(recipe, context={'request': request})
#         return Response(serializer.data)
#
#     def put(self, request, *args, **kwargs):
#         recipe_data = request.data
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeCreateSerializer(data=recipe_data, instance=recipe, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_200_OK)
#
#     def patch(self, request, *args, **kwargs):
#         recipe_data = request.data
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True).first()
#         if not recipe:
#             raise NotFound
#         serializer = RecipeCreateSerializer(data=recipe_data, instance=recipe,
#                                             partial=True, context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_200_OK)
#
#     def delete(self, request, *args, **kwargs):
#         recipe_id = kwargs.get('pk')
#         recipe = Recipe.objects.filter(pk=recipe_id, is_published=True)
#         if not recipe:
#             raise NotFound
#         recipe.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)

jbd-sprint4-day2-Abdiev003/stories/views.py
import math

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView
)

from stories.forms import ContactForm, RecipesForm
from stories.models import Recipe, Tag, Contact
from stories.tasks import dump_database


def dump_database_view(request):
    dump_database.delay()
    return HttpResponse('Database dump olundu...')


def HomePage(request):
    return render(request, "index.html")


def AboutPage(request):
    context = {
        "title": "About Stories",
        "description": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia",
        "dailyvisitors": 200,
        "stories": 200,
        "recipes": 300,
        "user": 40,
    }
    return render(request, "about.html", context)


def StoriesPage(request):
    return render(request, "strories.html", )


# @login_required
# def RecipesPage(request):
#     page = int(request.GET.get('page', 1))
#     per_count = 2
#     all_recipes_count = Recipe.objects.filter(is_published=True).count()
#     recipes = Recipe.objects.filter(is_published=True)[per_count*(page-1):page*per_count]
#     page_count = math.ceil(all_recipes_count/per_count)
#     page_range = range(1, page_count+1)
#     arr = ['idris', 'emrah', 'eli']
#     welcome_msg = '<h1>Welcome</h1>'
#     previous_page = page - 1 if not page == 1 else page
#     next_page = page + 1 if not page == page_count else page
#     context = {
#         'recipe_list': recipes,
#         'welcome_msg': welcome_msg,
#         'page_range': page_range,
#         'current_page': page,
#         'previous_page': previous_page,
#         'next_page': next_page,
#         'arr': arr
#     }
#     return render(request, "recipes.html", context)


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes.html'
    paginate_by = 2

    # context_object_name = 'recipe_list'
    # queryset = Recipe.objects.filter(is_published=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        tags = self.request.GET.get('tags')
        print(tags)
        queryset = queryset.filter(is_published=True)
        if tags:
            queryset = queryset.filter(tags__id=tags)
        return queryset


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipe-detail.html'
    context_object_name = 'recipe_tag'
    queryset = Recipe.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


# def ContactPage(request):
#     form = ContactForm()
#     if request.method == 'POST':
#         form = ContactForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Sizin muracietiniz qebul edildi.')
#             return redirect('/recipes/')
#     context = {
#         'form': form
#     }
#     return render(request, "contact.html", context)


class ContactView(CreateView):
    form_class = ContactForm
    # fields = '__all__'
    # model = Contact
    template_name = 'contact.html'
    success_url = reverse_lazy('stories:index')

    def form_valid(self, form):
        result = super(ContactView, self).form_valid(form)
        messages.success(self.request, 'Sizin muracietiniz qebul edildi.')
        return result


class CreateRecipeView(LoginRequiredMixin, CreateView):
    form_class = RecipesForm
    template_name = 'recipes-add.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateRecipeView, self).form_valid(form)


def like_recipe(request):
    if request.method == 'POST':
        liked_recipes = request.COOKIES.get('liked_recipes', '')
        recipe_id = request.POST.get('recipe_id')

        html = render_to_string('successfully_added.html')
        response = HttpResponse(html)
        if recipe_id not in liked_recipes.split(','):
            recipe_ids = f'{liked_recipes}{recipe_id},'
            request.session['recipe_ids'] = recipe_ids
            response.set_cookie('liked_recipes', recipe_ids)
        return response


def liked_recipe_page(request):
    liked_recipes = request.COOKIES.get('liked_recipes', '')
    print(dict(request.session))
    recipes = Recipe.objects.filter(id__in=list(map(int, liked_recipes.split(',')[:-1])))
    context = {
        'recipe_list': recipes,
        'liked_recipe_page': True
    }
    return render(request, "recipes.html", context)

jbd-sprint4-day2-Abdiev003/stories/templates/includes/footer.html
{% load custom_tags i18n %}

<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" method="post" id="subscribe-section" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" name="email" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                                <p id="form-error" class="alert text-left ">skdjnsdjnfsjn</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        {% get_categories True as published_categories %}
                        {% for category in published_categories %}
                            <li><a href="#" class="py-2 d-block">{{category}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View,
                                    San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929
                                        210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span
                                        class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                        <form action="{% url 'set_language' %}" method="post">
                          {% csrf_token %}
                          <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" />
                          <select onchange="this.form.submit()" name="language">
                            {% get_language_info_list for LANGUAGES as languages %}
                              {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                  {{ language.code }}
                                </option>
                              {% endfor %}
                          </select>
{#                          <input type="submit" value="Change" />#}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                        aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

jbd-sprint4-day2-Abdiev003/stories/templates/includes/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'stories:index' %}">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if '/' == request.path %} active {% endif %}"><a href="{% url 'stories:index' %}" class="nav-link">{% trans 'Home' %}</a></li>
                <li class="nav-item {% if 'about' in request.path %} active {% endif %}"><a href="{% url 'stories:about' %}" class="nav-link">{% trans 'About' %}</a></li>
                <li class="nav-item {% if 'stories' in request.path %} active {% endif %}"><a href="{% url 'stories:stories' %}" class="nav-link">Stories</a></li>
                <li class="nav-item {% if 'recipes' in request.path %} active {% endif %}"><a href="{% url 'stories:recipes' %}" class="nav-link">Reseptler</a></li>
                <li class="nav-item {% if 'contact' in request.path %} active {% endif %}"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>
            <li class="nav-item {% if 'liked_recipe_page' in request.path %} active {% endif %}"><a href="{% url 'stories:liked_recipe_page' %}" class="nav-link">Liked Recipes</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-black px-3 px-md-4 py-3">Log Out</a></li>
                {% else %}
                     <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>