jbd-sprint4-day2-Abdiev003/accounts/urls.py
from django.urls import path, re_path

from accounts.views import register, activate, login, logout, change_password, UserProfileView, UserEditProfileView

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})/$',
            activate, name='activate'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('change-password/', change_password, name='change_password'),
    path('user-profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('edit-profile/', UserEditProfileView.as_view(), name='edit_profile'),
]

jbd-sprint4-day2-Abdiev003/food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

from accounts.views import CustomAuthToken

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include("stories.urls")),
    path('api/', include('stories.api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/auth/login/', CustomAuthToken.as_view())
)

jbd-sprint4-day2-Abdiev003/stories/urls.py
from django.urls import path

from .views import (
    HomePage, AboutPage, StoriesPage, like_recipe, liked_recipe_page,
    RecipeListView,
    RecipeDetailView,
    ContactView,
    CreateRecipeView, dump_database_view
    # RecipesPage,
)

app_name = "stories"

urlpatterns = [
    path('', HomePage, name="index"),
    path('about/', AboutPage, name="about"),
    path('stories/', StoriesPage, name="stories"),
    path('recipes/', RecipeListView.as_view(), name="recipes"),
    path('create-recipe/', CreateRecipeView.as_view(), name="create_recipe"),
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('contact/', ContactView.as_view(), name="contact"),
    path('like/', like_recipe, name='like'),
    path('liked_recipe_page/', liked_recipe_page, name='liked_recipe_page'),
    path('dump-my-database/', dump_database_view, name='dump_database_view'),
]

jbd-sprint4-day2-Abdiev003/accounts/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True,)
    GENDER_CHOICES = (
        (True, 'Men'),
        (False, 'Woman'),
    )
    image = models.ImageField('Image', upload_to='profile_pictures', null=True, blank=True)
    bio = models.TextField('Bio', null=True, blank=True)
    gender = models.BooleanField('Gender', choices=GENDER_CHOICES, default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name']

    @property
    def profile_picture(self):
        if self.image:
            return self.image.url
        return 'https://www.pngfind.com/pngs/m/470-4703547_icon-user-icon-hd-png-download.png'

    def get_absolute_url(self):
        return reverse_lazy('accounts:user_profile', kwargs={'pk': self.id})

jbd-sprint4-day2-Abdiev003/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'class': 'form-control',
                                          'placeholder': 'Password'
                                          }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'class': 'form-control',
                                          'placeholder': 'Confirm Password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2',
            'gender',
            'bio',
            'image',
        )

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'First name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Last name'
            }),

            'gender': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Gender'
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Biography'
            })
        }

    # def clean(self):
    #     password1 = self.cleaned_data.get('password1')
    #     password2 = self.cleaned_data.get('password2')
    #     if password1 != password2:
    #         raise forms.ValidationError('password and confirm password is not same')
    #     return super().clean()


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=40, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email'
    }))
    password = forms.CharField(max_length=40, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password'
    }))
    #
    # class Meta:
    #     model = User
    #     fields = (
    #         'email',
    #         'password'
    #     )


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'bio', 'image')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'First name',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Last name',
            }),
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email',
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Biography',
            }),
        }

jbd-sprint4-day2-Abdiev003/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView, DetailView, UpdateView

from rest_framework.authtoken.views import ObtainAuthToken

from rest_framework.response import Response

from accounts.forms import RegistrationForm, LoginForm, EditProfileForm
from accounts.serializers import UserLoginSerializer
from accounts.tasks import send_confirmation_mail
from accounts.tools.tokens import account_activation_token

User = get_user_model()


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # http://example.com
            site_address = request.is_secure() and "https://" or "http://" + request.META['HTTP_HOST']  # https
            send_confirmation_mail(user_id=user.id, site_address=site_address)
            messages.success(request, 'Siz ugurla qeydiyyatdan kecdiniz')
            return redirect(reverse_lazy('stories:index'))
    context = {
        'form': form
    }
    return render(request, 'register.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Email is activated')
        return redirect(reverse_lazy('stories:index'))
    elif user:
        messages.error(request, 'Email is not activated. May be is already activated')
        return redirect(reverse_lazy('accounts:register'))
    else:
        messages.error(request, 'Email is not activated')
        return redirect(reverse_lazy('accounts:register'))


# http://localhost:8000/admin/login/?next=/admin/stories/recipe/1/change/1
def login(request):
    next_page = request.GET.get('next')  # /admin/stories/recipe/1/change/1
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(username=email, password=password)
            if user:
                django_login(request, user)
                messages.success(request, 'Siz ugurla daxil oldunuz')
                if next_page:
                    return redirect(next_page)
                return redirect(reverse_lazy('stories:index'))
            else:
                messages.success(request, 'Daxil etdiyiniz melumatlar yalnisdir')
    context = {
        'form': form
    }
    return render(request, 'login.html', context)


@login_required
def logout(request):
    django_logout(request)
    messages.success(request, 'Siz cixis etdiniz')
    return redirect(reverse_lazy('stories:index'))


@login_required
def change_password(request):
    print(request.user)
    return render(request, 'change_password.html')


class UserProfileView(DetailView):
    model = User
    template_name = 'user-profile.html'
    context_object_name = 'user'


class UserEditProfileView(LoginRequiredMixin, UpdateView):
    form_class = EditProfileForm
    model = User
    template_name = 'edit-profile.html'

    def get_object(self):
        return self.request.user

    # def get(self, request, *args, **kwargs):
    #     if not request.user == self.get_object():
    #         raise PermissionDenied
    #     return super(UserEditProfileView, self).get(request, *args, **kwargs)


class CustomAuthToken(ObtainAuthToken):

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        user_serializer = UserLoginSerializer(user)

        return Response(user_serializer.data, )

jbd-sprint4-day2-Abdiev003/accounts/templates/change_password.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Register' %}  {% endblock %}


{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Old password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="New password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Re-enter new password">
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

jbd-sprint4-day2-Abdiev003/accounts/templates/edit-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Account {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        {{ form.non_field_errors }}
                        {% csrf_token %}
                        <a class="navbar-brand center" href="{% url 'stories:index' %}">Stories<span>.</span></a>
                        {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                            {% for error in field.errors %}
                                <li class="alert alert-danger">{{ error }}</li>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <div class="form-group">
                            <input type="submit" value="Edit Profile" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

jbd-sprint4-day2-Abdiev003/accounts/templates/forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="../css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="../css/animate.css">

    <link rel="stylesheet" href="../css/owl.carousel.min.css">
    <link rel="stylesheet" href="../css/owl.theme.default.min.css">
    <link rel="stylesheet" href="../css/magnific-popup.css">

    <link rel="stylesheet" href="../css/aos.css">

    <link rel="stylesheet" href="../css/ionicons.min.css">

    <link rel="stylesheet" href="../css/flaticon.css">
    <link rel="stylesheet" href="../css/icomoon.css">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/custom.css">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="index.html" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
                <li class="nav-item"><a href="strories.html" class="nav-link">Stories</a></li>
                <li class="nav-item"><a href="recipes.html" class="nav-link">Recipes</a></li>
                <li class="nav-item active"><a href="contact.html" class="nav-link">Contact</a></li>
                <li><a href="" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->
 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="../js/jquery.min.js"></script>
<script src="../js/jquery-migrate-3.0.1.min.js"></script>
<script src="../js/popper.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
<script src="../js/jquery.easing.1.3.js"></script>
<script src="../js/jquery.waypoints.min.js"></script>
<script src="../js/jquery.stellar.min.js"></script>
<script src="../js/owl.carousel.min.js"></script>
<script src="../js/jquery.magnific-popup.min.js"></script>
<script src="../js/aos.js"></script>
<script src="../js/jquery.animateNumber.min.js"></script>
<script src="../js/scrollax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="../js/google-map.js"></script>
<script src="../js/main.js"></script>

</body>
</html>

jbd-sprint4-day2-Abdiev003/accounts/templates/register.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Register' %}  {% endblock %}


{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="post" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {{ form.non_field_errors }}
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                            {{ field.help_text }}
                            {% for error in field.errors %}
                                <li class="alert-danger alert">{{ error }}</li>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

jbd-sprint4-day2-Abdiev003/accounts/templates/user-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} User Profile Page {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}


<section class="ftco-section ftco-no-pt ">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="user-profile-side-bar sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{{ user.profile_picture }}" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>{{ user.first_name }} {{ user.last_name }}</strong>, {{ user.bio }}</p>
                        </div>
                    </div>
                    {% if request.user.is_authenticated and user == request.user  %}
                    <div class="sidebar-box ftco-animate user-profile">

                        <a href="{% url 'accounts:edit_profile' %}" class="btn btn-hover-color py-2">Edit Profile</a>

                    </div>

                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'accounts:change_password' %}" class="btn btn-hover-color py-2">Change Password </a>
                    </div>
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="" class="btn btn-hover-color py-2">Create story </a>
                    </div>
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'stories:create_recipe' %}" class="btn btn-hover-color py-2">Create recipe </a>
                    </div>
                    {% endif %}
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>My stories and recipes</span></h2>
                    </div>
                </div>
                <div class="row">

                        {% for user_story in user.recipes.all %}
                            <div class="col-md-4 ftco-animate">
                                <div class="blog-entry">
                            <a class="img-2">

                                <div class="user-events__edit">
                                    <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                    <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </div>

                                <img src="{{ user_story.image.url }}" class="img-fluid" alt="{{ user_story.title }}">
                            </a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{ user_story.category__title }}</span>
                                    <span class="ml-auto pl-3">{{ user_story.created_at|date:"F d, Y" }}</span>
                                </p>
                                <h3><a href="#">{{ user_story.title }}</a></h3>
                                <p class="mb-0"><a href="{{ user_story.get_absolute_url }}" class="btn btn-black py-2">Read More <span
                                    class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                            </div>
                        {% endfor %}
                </div>
                <div class="row">
                        {% for user_recipe in user.stories.all %}
                            <div class="col-md-4 ftco-animate">
                                <div class="blog-entry">
                            <a class="img-2">

                                <div class="user-events__edit">
                                    <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                    <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </div>

                                <img src="{{ user_recipe.image.url }}" class="img-fluid" alt="{{ user_recipe.title }}">
                            </a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{ user_recipe.category__title }}</span>
                                    <span class="ml-auto pl-3">{{ user_recipe.created_at|date:"F d, Y" }}</span>
                                </p>
                                <h3><a href="#">{{ user_recipe.title }}</a></h3>
                                <p class="mb-0"><a href="{{ user_recipe.get_absolute_url }}" class="btn btn-black py-2">Read More <span
                                    class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}